sudo: required
dist: trusty

services:
  - docker

language: go
go:
  - 1.8

branches:
  only:
    - master

before_install:
  - sudo apt-get update

install:
  - go get github.com/openebs/mayaserver/cmd
  - make init
  - make

script:
  - make bin 
  - ls -la pkg/
  - ./buildscripts/test-cov.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - make image 
  
deploy:
  provider: releases
  api_key:
    secure: gixl7UUJK7XlzH9TjLx3JnBPFgHFt7goC6xd0BYoGYPNNKIDKHmc2afXrF/CBSKU/afwVMctHqGbj0bqG+jDVIC6nRoEwz64JaByJpOZZWvDi/Qknu0IzjOrUVS1YPfxddJ/DJzy28APNima2vRbS7QJLds/LGgj3lSp+BWp7eLWNq7Gw6IXtX3mL8AS3YpEHTeoO5E8EiHHoz1QIoXrszpsXCRF0+R1/4MvcfPv//4hJ5wyEYOSwCK1eEwi1BaPy/BtI3DC62LnF4JRkVJb7F31VrnLAevJfUgoUhKi1nadu0Idy71A9SITYhhxKXamgp/X93ig51jbMT0wYiz5+S3DkgtcDaYf389uyaHrgphbzjs/IFFTa2o5yGgh5A8oGWy1Pdd6gzFf+bftFkYtzkTECNZKjNd4Ft5e55CzpVOt2Z9oSD0NuMZtgkM9sz0Rs1IiCW/Y73o6dV4Z7sxY2nCbO6iNgW0bUEIk9l2wFJEN0+LGENaR7+aRkH6NesNk+bIOhY4lbHIis8fMTrkzOSQWVnjNs+7LJrA3GuokhsIMmJO8h9A5gd0K5QpYdIu4UQJH0M7LiEz16LnKK4+/h7OpgensKgC+MEwR8hSNDeeQZFx88R/vb/fLA1JwyeRyON6paD3K65ibODJIrxBZSV9AtXq0NyiOIRMUHKgZGEs=
  file_glob: true
  file: pkg/*-linux_*.zip
  skip_cleanup: true
  overwrite: true
  on:
    repo: maheshreddy7797/mayaserver
    tags: true
branches:
  except:
    - /^*-v[0-9]/
